AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for EC2 instance'
Metadata:
  Name: ec2.yaml
  Author: 'Tarun'
  Date: '2025-03-23'
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: 'ami-084568db4383264d4'
      InstanceType: 't2.micro'
      KeyName: 'new_key'
      VpcId: 'vpc-031233929013b8e88'
      SecurityGroupIds:
        - 'sg-0efaf36ae6c65c448'
      AvailabilityZone: 'us-east-1a'
      Tags:
        - Key: Name
          Value: 'EC2Instance'